window.PREP_TOPICS = [
  { id: "javascript", title: "JavaScript", category: "Frontend", icon: "🟨", blurb: "Core JS, ES6+, async, DOM, and interview patterns." },
  { id: "react", title: "React", category: "Frontend", icon: "⚛️", blurb: "Components, hooks, state, routing, and performance." },
  { id: "typescript", title: "TypeScript", category: "Frontend", icon: "🔷", blurb: "Types, generics, utility types, and real-world TS." },
  { id: "htmlcss", title: "HTML & CSS", category: "Frontend", icon: "🎨", blurb: "Semantic HTML, layout, responsive design, and CSS tricks." },
  { id: "nodeexpress", title: "Node.js & Express", category: "Backend", icon: "🟩", blurb: "Runtime, APIs, middleware, auth, and Node internals." },
  { id: "fullstack", title: "Full Stack", category: "Backend", icon: "🧩", blurb: "End-to-end apps, REST, auth, caching, and architecture." },
  { id: "sql", title: "SQL & Databases", category: "Backend", icon: "🗄️", blurb: "Queries, indexes, transactions, and relational design." },
  { id: "database", title: "Databases", category: "Data stores", icon: "🗃️", blurb: "OLTP vs OLAP, ACID, replicas, shards, and how to pick a store." },
  { id: "mongodb", title: "MongoDB", category: "Backend", icon: "🍃", blurb: "Documents, aggregations, indexes, and schema design." },
  { id: "nosql", title: "NoSQL", category: "Data stores", icon: "📄", blurb: "Document, key-value, wide-column, and graph — when each wins." },
  { id: "vectordb", title: "Vector databases", category: "Data stores", icon: "🧭", blurb: "Embeddings, RAG, pgvector, Pinecone, and similarity search." },
  { id: "git", title: "Git & GitHub", category: "Tools", icon: "🌿", blurb: "Commands, commits, branches, PRs, rebase — plus the questions companies ask." },
  { id: "postman", title: "Postman & API tools", category: "Tools", icon: "📬", blurb: "Postman, curl, Thunder Client, Swagger — test APIs with commands and interview Qs." },
  { id: "linux", title: "Linux", category: "Tools", icon: "🐧", blurb: "Commands, processes, permissions, and shell basics." },
  { id: "docker", title: "Docker", category: "DevOps", icon: "🐳", blurb: "Images, containers, volumes, networks, and Compose." },
  { id: "kubernetes", title: "Kubernetes", category: "DevOps", icon: "☸️", blurb: "Pods, services, deployments, and cluster basics." },
  { id: "devops", title: "DevOps", category: "DevOps", icon: "🔁", blurb: "CI/CD, IaC, monitoring, and delivery practices." },
  { id: "aws", title: "AWS", category: "Cloud", icon: "☁️", blurb: "EC2, S3, IAM, VPC, Lambda, and common interview topics." },
  { id: "python", title: "Python", category: "ML / Data", icon: "🐍", blurb: "Syntax, lists, functions, files, and beginner Python." },
  { id: "machinelearning", title: "Machine Learning", category: "ML / Data", icon: "🧠", blurb: "Train/test, models, metrics, and simple ML ideas." },
  { id: "dsa-arrays", title: "Arrays", category: "DSA / Interview", icon: "📦", blurb: "FAANG array problems: Two Sum, Kadane, intervals, and more." },
  { id: "dsa-strings", title: "Strings", category: "DSA / Interview", icon: "🔤", blurb: "Anagrams, windows, palindromes, and string FAANG classics." },
  { id: "dsa-linkedlist", title: "Linked List", category: "DSA / Interview", icon: "🔗", blurb: "Reverse, cycle, merge, and the lists FAANG asks every year." },
  { id: "dsa-tree", title: "Binary Trees", category: "DSA / Interview", icon: "🌳", blurb: "DFS, BFS, views, paths, and binary-tree interview staples." },
  { id: "dsa-bst", title: "BST", category: "DSA / Interview", icon: "🌲", blurb: "Search, insert, delete, and the BST questions FAANG loves." },
  { id: "dsa-binarysearch", title: "Binary Search", category: "DSA / Interview", icon: "🎯", blurb: "Low/high, rotated arrays, peaks, and answer-space search." },
  { id: "dsa-backtracking", title: "Recursion & Backtracking", category: "DSA / Interview", icon: "↩️", blurb: "Subsets, permutations, N-Queens, mazes, and undo-a-choice." },
  { id: "dsa-trie", title: "Tries", category: "DSA / Interview", icon: "🔠", blurb: "Prefix trees: autocomplete, word search, and dictionary design." },
  { id: "dsa-graph", title: "Graphs", category: "DSA / Interview", icon: "🕸️", blurb: "Islands, courses, BFS/DFS, and shortest-path patterns." },
  { id: "dsa-stackheap", title: "Stack, Queue & Heap", category: "DSA / Interview", icon: "📚", blurb: "Monotonic stack, top-K, sliding window max, and heaps." },
  { id: "dsa-dp", title: "Dynamic Programming", category: "DSA / Interview", icon: "♟️", blurb: "Climb stairs, knapsack, LIS, and the DP questions FAANG loves." },
  { id: "sys-blocks", title: "System Design Blocks", category: "System Design", icon: "🏗️", blurb: "DNS, load balancers, cache, CDN, queues, sharding, and CAP — with diagrams." },
  { id: "sys-cases", title: "System Design Cases", category: "System Design", icon: "🗺️", blurb: "URL shortener, feed, chat, rate limiter, and other interview designs with workflows." },
  { id: "redis", title: "Redis", category: "Backend", icon: "🔴", blurb: "In-memory cache, sessions, TTL, rate limits, and when not to use Redis." },
  { id: "nginx", title: "Nginx", category: "DevOps", icon: "🟩", blurb: "Reverse proxy, static files, HTTPS, load balancing, and VPS layouts." },
  { id: "hosting", title: "Vercel, Render & Hosting", category: "DevOps", icon: "🚀", blurb: "Vercel, Render, Netlify, Railway — Git to HTTPS, env vars, and split UI/API." },
  { id: "messaging", title: "Queues & Kafka", category: "Backend", icon: "📬", blurb: "RabbitMQ, Kafka, SQS, workers, retries, and dead-letter queues." },
  { id: "practice-web", title: "JS & Web interview", category: "Practice", icon: "🌐", blurb: "var/let/const, event loop, HTTP, DNS, CORS, JWT, XSS — answers plus easy commented examples." },
  { id: "practice-dom", title: "Card & DOM projects", category: "Practice", icon: "🃏", blurb: "Show cards, click listeners, delegation, add/delete, search, modal, localStorage." },
  { id: "practice-frontend", title: "Frontend practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked interviews: CORS, XSS, JWT storage, React keys, HTTPS." },
  { id: "practice-backend", title: "Backend practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: REST, JWT vs session, 401/403, SQL injection, ACID." },
  { id: "practice-mern", title: "MERN practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: MERN flow, CORS, Mongo vs SQL, JWT, ObjectId." },
  { id: "practice-fullstack", title: "Full stack practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: click-to-SQL, XSS vs CSRF, cache-aside, deploy." },
  { id: "practice-devops", title: "DevOps practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: CI vs CD, containers, blue-green, health, secrets." },
  { id: "practice-cloud", title: "Cloud practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: IAM, VPC, S3 vs EBS, EC2 vs Lambda, Multi-AZ." },
  { id: "practice-ml", title: "ML practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: overfit, precision/recall, bias/variance, leakage." },
  { id: "practice-data", title: "Data practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: WHERE vs HAVING, JOINs, GROUP BY, OLTP vs warehouse." },
  { id: "practice-datastores", title: "Data stores practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: SQL vs NoSQL, Redis, CAP, replica vs shard, vectors." },
  { id: "practice-sysdesign", title: "System design practice", category: "Practice", icon: "🧪", blurb: "Labs plus most-asked: shortener, rate limiter, CAP, cache, CDN, queues." }
];

window.PREP_DATA = window.PREP_DATA || {};
