module.exports = []
  .concat(require("./g_ex.cjs"))
  .concat(require("./g_q1.cjs"))
  .concat(require("./g_q2.cjs"))
  .concat(require("./g_q3.cjs"))
  .concat(require("./g_q4.cjs"))
  .concat(require("./g_q5.cjs"))
  .concat(require("./g_q6.cjs"))
  .concat(require("./g_q7.cjs"))
  .concat(require("./g_q8.cjs"))
  .concat(require("./g_q9.cjs"))
  .concat(require("./g_q10.cjs"))
  .concat(require("./g_q11.cjs"))
  .concat(require("./g_q12.cjs"))
  .concat(require("./g_q13.cjs"))
  .concat(require("./g_q14.cjs"))
  .concat(require("./g_q15.cjs"));
